[package]
name = "regionoix-backend"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
actix-web = { workspace = true }
sea-orm = { workspace = true }