DROP TABLE IF EXISTS DISCOUNT;

DROP TABLE IF EXISTS CART_LINE;

DROP TABLE IF EXISTS CART;

DROP TABLE IF EXISTS ORDER_LINE;

DROP TABLE IF EXISTS ORDER_;

DROP TABLE IF EXISTS PRODUCT_CATEGORY;

DROP TABLE IF EXISTS PRODUCT_TAG;

DROP TABLE IF EXISTS TAG;

DROP TABLE IF EXISTS PRODUCT;

DROP TABLE IF EXISTS USER_;

DROP TABLE IF EXISTS SUB_CATEGORY;

DROP TABLE IF EXISTS CATEGORY;

DROP TABLE IF EXISTS REGION;

DROP TABLE IF EXISTS BRAND;