//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "product")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub weight: Option<f64>,
    #[sea_orm(column_type = "Float")]
    pub price: f32,
    pub image: Option<String>,
    pub stock: i32,
    pub region_id: Option<i32>,
    pub brand_id: Option<i32>,
    pub category_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::brand::Entity",
        from = "Column::BrandId",
        to = "super::brand::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Brand,
    #[sea_orm(has_many = "super::cart_line::Entity")]
    CartLine,
    #[sea_orm(
        belongs_to = "super::category::Entity",
        from = "Column::CategoryId",
        to = "super::category::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Category,
    #[sea_orm(has_many = "super::discount::Entity")]
    Discount,
    #[sea_orm(has_many = "super::order_line::Entity")]
    OrderLine,
    #[sea_orm(has_many = "super::product_tag::Entity")]
    ProductTag,
    #[sea_orm(
        belongs_to = "super::region::Entity",
        from = "Column::RegionId",
        to = "super::region::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Region,
}

impl Related<super::brand::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Brand.def()
    }
}

impl Related<super::cart_line::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CartLine.def()
    }
}

impl Related<super::category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Category.def()
    }
}

impl Related<super::discount::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Discount.def()
    }
}

impl Related<super::order_line::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderLine.def()
    }
}

impl Related<super::tag::Entity> for Entity {
    fn to() -> RelationDef {
        super::product_tag::Relation::Tag.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::product_tag::Relation::Product.def().rev())
    }
}

impl Related<super::region::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Region.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
