//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sub_category")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub main_category_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub sub_category_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::category::Entity",
        from = "Column::MainCategoryId",
        to = "super::category::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Category2,
    #[sea_orm(
        belongs_to = "super::category::Entity",
        from = "Column::SubCategoryId",
        to = "super::category::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Category1,
}

impl ActiveModelBehavior for ActiveModel {}
