name: Check backend

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'src/**' # Frontend
      - 'nix/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'src/**' # Frontend
      - 'nix/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  check:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
    - uses: actions/checkout@v4
    - name: Setup rust toolchain
      run: |
        rustup update ${{ matrix.toolchain }}
        rustup default ${{ matrix.toolchain }}
    - name: Install lint components
      run: |
        rustup component add rustfmt --toolchain ${{ matrix.toolchain }}
    - name: Print Rust and Clippy versions
      run: |
        rustc --version
        cargo clippy --version
    - name: Lint (rustfmt)
      run: cargo fmt --all --check
    - name: Test (cargo)
      run: cargo test
