name: "Check Nix"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-25.05
    - uses: cachix/cachix-action@v14
      with:
        name: gasdev-cachix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build --no-link --print-out-paths .#regionoix-backend .#regionoix-frontend

