name: Deploy

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Nix deployment
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
          nix_path: nixpkgs=channel:nixos-25.05
    - uses: cachix/cachix-action@v14
      with:
        name: gasdev-cachix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Set up SSH key
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "Deploying to ${{ vars.DEPLOY_HOST }}"
          ssh-keyscan -p 22 ${{ vars.DEPLOY_HOST }} >> ~/.ssh/known_hosts
    - name: Fix SSH env
      run: echo "SetEnv PATH=/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" >> /etc/ssh/sshd_config
    - name: Deploy to Raviole1 with deploy-rs
      shell: 'nix develop -c bash -e {0}'
      run: deploy .#Raviole1

