name: Deploy

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Nix deployment
    steps:
    - uses: actions/checkout@v4
    - name: Set up SSH key
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "Deploying to ${{ vars.DEPLOY_HOST }}"
          ssh-keyscan -p 22 ${{ vars.DEPLOY_HOST }} >> ~/.ssh/known_hosts
    - uses: cachix/install-nix-action@v31
      with:
          nix_path: nixpkgs=channel:nixos-25.05
    - name: Run a command with nix develop
      shell: 'nix develop --ignore-environment -c bash -e {0}'
      run: deploy .#Raviole1

